- name: Copy jmx exporter config
  template:
    src: jmx_config.yml.j2
    dest: "{{ jmx_exporter_conf_path }}"
    owner: "{{ jmx_exporter_system_user }}"
    group: "{{ jmx_exporter_system_group }}"
    mode: 0640
  notify:
    - restart jmx_exporter


- name: Allow JMX Exporter port in SELinux on RedHat OS family
  seport:
    ports: "{{ jmx_exporter_listen_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"