---
- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ jmx_exporter_dependencies }}"

- name: Create the jmx exporter group
  group:
    name: "{{ jmx_exporter_system_group }}"
    state: present
    system: true

- name: Create the jmx exporter user
  user:
    name: "{{ jmx_exporter_system_user }}"
    groups: "{{ jmx_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /

- name: Ensure the jmx exporter bin and config paths
  file:
    dest: "{{ item }}"
    owner: "{{ jmx_exporter_system_user }}"
    group: "{{ jmx_exporter_system_group }}"
    state: directory
  with_items:
    - "{{ jmx_exporter_root_directory }}"
    - "{{ jmx_exporter_conf_directory }}"

- name: Download jmx exporter binary
  become: false
  get_url:
    url: "{{ jmx_exporter_url }}"
    dest: "/tmp/{{ jmx_exporter_file }}"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: Propagate jmx exporter binary
  copy:
    src: "/tmp/{{ jmx_exporter_file }}"
    dest: "{{ jmx_exporter_jar_path }}"
    mode: 0750
    owner: "{{ jmx_exporter_system_user }}"
    group: "{{ jmx_exporter_system_group }}"
  notify: restart jmx_exporter
  when: not ansible_check_mode