---
- name: Fail on unsupported init systems
  fail:
    msg: "This module only works with systemd"
  when: ansible_service_mgr != 'systemd'

- name: Get sha1 checksum
  set_fact:
    _jar_checksum: "{{ lookup('url', jmx_exporter_url_sha1) }}"
  run_once: true
